baseURL = 'http://alexstewart.uk/'
languageCode = 'en-gb'
title = 'Alex Stewart'
theme = 'hugo-texify2'

[params]
title = 'Alex Stewart'
footnote = ""
enableDuckDuckGoSearchBox = false

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/"
weight = 1
[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/post/"
weight = 2